-- total costomer by country

SELECT
country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- total customer by gender

SELECT
gender, COUNT(customer_key) AS total_customers_by_gender
FROM gold.dim_customers
GROUP BY gender
-- total products by category

SELECT
category, COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC

-- what is the average costs in each category
SELECT
category, AVG(cost) AS avg_product
FROM gold.dim_products
GROUP BY category
ORDER BY avg_product DESC

-- what is the total revenue generated for each category
SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- find total revenue is generated by each customer

SELECT TOP 10
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 	c.customer_key,
			c.first_name,
			c.last_name
ORDER BY total_revenue DESC

-- what is the distrbution of sold items across countries
SELECT
	c.country,
	SUM(f.quantity) AS total_sold_item,
    ROUND(100* SUM(f.quantity) / SUM(SUM(f.quantity)) OVER(),2) AS percent_of_total
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_item DESC
